[project]
name = "dispytch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "aiokafka>=0.12.0",
    "msgpack>=1.1.1",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.0.0",
]
