[project]
name = "fast-api-example"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dispytch[rabbitmq]>=0.9.0",
    "fastapi>=0.116.0",
    "pydantic-settings>=2.10.1",
]
