site_name: Dispytch
repo_url: https://github.com/e1-m/dispytch
repo_name: e1-m/dispytch
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.tabs.link
extra:
  version:
    provider: mike
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Tutorial:
      - Dependency Injection: tutorial/di/di.md
      - Events:
          - Emitting Events: tutorial/events/emitter.md
          - Handling Events: tutorial/events/dispatcher.md
          - Dynamic Routes: tutorial/events/dynamic_routes.md
          - Serialization: tutorial/events/serialization.md
      - Middleware:
          - General: tutorial/middleware/middleware.md
          - Retries: tutorial/middleware/retries.md
          - Exception Handling: tutorial/middleware/exception_handling.md
          - Filtering: tutorial/middleware/filter.md
          - Async Lock: tutorial/middleware/async_lock.md
      - Async Processing: tutorial/async_processing/async_processing.md
      - Advanced Usage:
          - Custom Producers & Consumers: tutorial/advanced/own_consumers_and_producers.md
          - Backend Configuration: tutorial/advanced/backend_specific_event_configs.md