site_name: Dispytch
repo_url: https://github.com/e1-m/dispytch
repo_name: e1-m/dispytch
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.tabs.link
markdown_extensions:
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Core Concepts:
      - Architecture Overview: concepts/architecture.md
      - Dependency Injection: concepts/di.md
      - Event Emitter: concepts/emitter.md